apiVersion: cert-manager.k8s.cloudflare.com/v1
kind: OriginIssuer
metadata:
  name: {{ .Values.name }}
spec:
  requestType: OriginECC
  auth:
    serviceKeyRef:
      name: {{ .Values.name }}-key
      key: key
